version: "2.1"

volumes:
  db_data:
    driver: local

services:
  news-mysql:
    container_name: news-mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - news-mysql
    ports:
      - 5001:8080

  web:
    build: .
    container_name: web
    tty: true
    restart: unless-stopped
    depends_on:
      - news-mysql
    links:
      - "news-mysql:mysql_db"
      - "news-redis:redis_db"
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./:/app/
      - ./volumes/logs:/var/log

  news-redis:
    image: redis:4.0.9
    container_name: news-redis
    ports:
      - "6379:6379"


