version: "2.1"

volumes:
  db_data:
    driver: local

services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "33065:3306"
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080

  web:
    build: .
    container_name: web
    restart: always
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    volumes:
      - ./:/app/
